const NS="http://www.w3.org/2000/svg";
const $=id=>document.getElementById(id);
const canvas=$("canvas"), objects=$("objects"), selectionLayer=$("selectionLayer");
let tool="select", selected=null, drawing=null, start=null, drag=null, zoom=1;
let history=[], historyIndex=-1, restoring=false;

function snapshot(){if(restoring)return;const s=objects.innerHTML+"||"+$("artboard").getAttribute("fill");if(history[historyIndex]===s)return;history=history.slice(0,historyIndex+1);history.push(s);historyIndex=history.length-1}
function restore(i){if(i<0||i>=history.length)return;restoring=true;historyIndex=i;const [o,b]=history[i].split("||");objects.innerHTML=o;$("artboard").setAttribute("fill",b);$("background").value=b;select(null);refreshLayers();restoring=false}
function svgPoint(e){const p=canvas.createSVGPoint();p.x=e.clientX;p.y=e.clientY;return p.matrixTransform(canvas.getScreenCTM().inverse())}
function setTool(name){tool=name;document.querySelectorAll(".tool[data-tool]").forEach(b=>b.classList.toggle("active",b.dataset.tool===name));$("status").textContent=name[0].toUpperCase()+name.slice(1);canvas.style.cursor=name==="select"?"default":"crosshair"}
function make(tag,attrs={}){const el=document.createElementNS(NS,tag);for(const [k,v] of Object.entries(attrs))el.setAttribute(k,v);return el}
function styleNew(el){el.setAttribute("fill",$("fill").value);el.setAttribute("stroke",$("stroke").value);el.setAttribute("stroke-width",$("strokeWidth").value);el.setAttribute("opacity",$("opacity").value/100);el.dataset.name=el.tagName.toLowerCase()}
function select(el){selected=el;selectionLayer.innerHTML="";document.querySelectorAll(".layer").forEach(x=>x.classList.remove("active"));if(!el){clearTransform();return}drawSelection();syncControls();const row=document.querySelector('[data-id="'+el.id+'"]');if(row)row.classList.add("active")}
function drawSelection(){selectionLayer.innerHTML="";if(!selected)return;const b=selected.getBBox();selectionLayer.appendChild(make("rect",{x:b.x-4,y:b.y-4,width:b.width+8,height:b.height+8,class:"selection-box"}))}
function ensureId(el){if(!el.id)el.id="obj_"+Date.now()+"_"+Math.floor(Math.random()*9999)}
function refreshLayers(){const box=$("layers");box.innerHTML="";const list=[...objects.children].reverse();if(!list.length){box.innerHTML='<div class="empty">Nenhum objeto</div>';return}list.forEach((el,i)=>{ensureId(el);const row=document.createElement("div");row.className="layer"+(el===selected?" active":"");row.dataset.id=el.id;row.innerHTML='<span class="layer-icon">'+({rect:"□",ellipse:"○",line:"╱",text:"T"}[el.tagName.toLowerCase()]||"◆")+'</span><span>'+(el.dataset.name||el.tagName)+"</span>";row.onclick=()=>select(el);box.appendChild(row)})}
function bbox(){return selected?selected.getBBox():null}
function syncControls(){if(!selected)return;const b=bbox();$("posX").value=Math.round(b.x);$("posY").value=Math.round(b.y);$("sizeW").value=Math.round(b.width);$("sizeH").value=Math.round(b.height);$("fill").value=normalizeColor(selected.getAttribute("fill"),"#69a7ff");$("stroke").value=normalizeColor(selected.getAttribute("stroke"),"#172033");$("strokeWidth").value=selected.getAttribute("stroke-width")||0;$("strokeValue").value=$("strokeWidth").value;$("opacity").value=Math.round((selected.getAttribute("opacity")||1)*100);$("opacityValue").value=$("opacity").value+"%"}
function normalizeColor(c,f){return c&&/^#[0-9a-f]{6}$/i.test(c)?c:f}
function clearTransform(){["posX","posY","sizeW","sizeH"].forEach(id=>$(id).value="")}
function moveBy(el,dx,dy){const t=el.tagName.toLowerCase();if(t==="rect"||t==="text"){el.setAttribute("x",(+el.getAttribute("x")||0)+dx);el.setAttribute("y",(+el.getAttribute("y")||0)+dy)}else if(t==="ellipse"){el.setAttribute("cx",(+el.getAttribute("cx")||0)+dx);el.setAttribute("cy",(+el.getAttribute("cy")||0)+dy)}else if(t==="line"){["x1","x2"].forEach(a=>el.setAttribute(a,+el.getAttribute(a)+dx));["y1","y2"].forEach(a=>el.setAttribute(a,+el.getAttribute(a)+dy))}}
function deleteSelected(){if(!selected)return;selected.remove();selected=null;selectionLayer.innerHTML="";refreshLayers();snapshot()}
function duplicate(){if(!selected)return;const c=selected.cloneNode(true);c.id="";ensureId(c);moveBy(c,12,12);objects.appendChild(c);select(c);refreshLayers();snapshot()}
canvas.addEventListener("pointerdown",e=>{const p=svgPoint(e);start=p;if(tool==="select"){const target=e.target.closest("#objects > *");select(target||null);if(selected){drag={p,box:selected.getBBox()};canvas.setPointerCapture(e.pointerId)}return}if(tool==="text"){const text=prompt("Texto:","LS");if(!text)return;drawing=make("text",{x:p.x,y:p.y,"font-size":72,"font-family":"Arial, sans-serif","font-weight":"700"});styleNew(drawing);drawing.textContent=text;ensureId(drawing);objects.appendChild(drawing);select(drawing);refreshLayers();snapshot();setTool("select");return}const attrs=tool==="rect"?{x:p.x,y:p.y,width:1,height:1,rx:18}:tool==="ellipse"?{cx:p.x,cy:p.y,rx:1,ry:1}:{x1:p.x,y1:p.y,x2:p.x,y2:p.y};drawing=make(tool,attrs);styleNew(drawing);if(tool==="line")drawing.setAttribute("fill","none");ensureId(drawing);objects.appendChild(drawing);canvas.setPointerCapture(e.pointerId)});
canvas.addEventListener("pointermove",e=>{const p=svgPoint(e);if(drag&&selected){moveBy(selected,p.x-drag.p.x,p.y-drag.p.y);drag.p=p;drawSelection();syncControls();return}if(!drawing||!start)return;const x=Math.min(start.x,p.x),y=Math.min(start.y,p.y),w=Math.abs(p.x-start.x),h=Math.abs(p.y-start.y);if(tool==="rect"){Object.entries({x,y,width:w,height:h}).forEach(([k,v])=>drawing.setAttribute(k,v))}else if(tool==="ellipse"){drawing.setAttribute("cx",(start.x+p.x)/2);drawing.setAttribute("cy",(start.y+p.y)/2);drawing.setAttribute("rx",w/2);drawing.setAttribute("ry",h/2)}else{drawing.setAttribute("x2",p.x);drawing.setAttribute("y2",p.y)}});
canvas.addEventListener("pointerup",()=>{if(drag){drag=null;snapshot()}if(drawing){select(drawing);drawing=null;refreshLayers();snapshot();setTool("select")}});
document.querySelectorAll(".tool[data-tool]").forEach(b=>b.onclick=()=>setTool(b.dataset.tool));
$("deleteBtn").onclick=deleteSelected;$("duplicateBtn").onclick=duplicate;
$("fill").oninput=e=>{if(selected&&selected.tagName!=="line"){selected.setAttribute("fill",e.target.value);drawSelection()}};$("fill").onchange=snapshot;
$("stroke").oninput=e=>{if(selected)selected.setAttribute("stroke",e.target.value)};$("stroke").onchange=snapshot;
$("strokeWidth").oninput=e=>{$("strokeValue").value=e.target.value;if(selected)selected.setAttribute("stroke-width",e.target.value)};$("strokeWidth").onchange=snapshot;
$("opacity").oninput=e=>{$("opacityValue").value=e.target.value+"%";if(selected)selected.setAttribute("opacity",e.target.value/100)};$("opacity").onchange=snapshot;
$("background").oninput=e=>$("artboard").setAttribute("fill",e.target.value);$("background").onchange=snapshot;
function transformInput(){if(!selected)return;const b=bbox(),nx=+$("posX").value,ny=+$("posY").value,nw=Math.max(1,+$("sizeW").value),nh=Math.max(1,+$("sizeH").value);moveBy(selected,nx-b.x,ny-b.y);const t=selected.tagName.toLowerCase();if(t==="rect"){selected.setAttribute("width",nw);selected.setAttribute("height",nh)}else if(t==="ellipse"){selected.setAttribute("rx",nw/2);selected.setAttribute("ry",nh/2)}drawSelection();snapshot()}
["posX","posY","sizeW","sizeH"].forEach(id=>$(id).onchange=transformInput);
function setZoom(v){zoom=Math.max(.25,Math.min(2,v));canvas.style.width=512*zoom+"px";canvas.style.height=512*zoom+"px";$("zoomLabel").textContent=Math.round(zoom*100)+"%"}$("zoomIn").onclick=()=>setZoom(zoom+.25);$("zoomOut").onclick=()=>setZoom(zoom-.25);
$("undoBtn").onclick=()=>restore(historyIndex-1);$("redoBtn").onclick=()=>restore(historyIndex+1);
$("newBtn").onclick=()=>{if(objects.children.length&&!confirm("Limpar o desenho atual?"))return;objects.innerHTML="";$("artboard").setAttribute("fill","#ffffff");$("background").value="#ffffff";select(null);refreshLayers();snapshot()};
function cleanSvg(){const clone=canvas.cloneNode(true);clone.querySelector("#selectionLayer").remove();clone.removeAttribute("style");clone.setAttribute("width","512");clone.setAttribute("height","512");return new XMLSerializer().serializeToString(clone)}
function download(blob,name){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$("exportSvg").onclick=()=>download(new Blob([cleanSvg()],{type:"image/svg+xml"}),"icon.svg");
$("exportPng").onclick=()=>{const img=new Image(),url=URL.createObjectURL(new Blob([cleanSvg()],{type:"image/svg+xml"}));img.onload=()=>{const c=document.createElement("canvas");c.width=c.height=512;const ctx=c.getContext("2d");ctx.drawImage(img,0,0);c.toBlob(b=>download(b,"icon.png"),"image/png");URL.revokeObjectURL(url)};img.src=url};
window.addEventListener("keydown",e=>{if((e.key==="Delete"||e.key==="Backspace")&&selected){e.preventDefault();deleteSelected()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="d"){e.preventDefault();duplicate()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="z"){e.preventDefault();restore(historyIndex-1)}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="y"){e.preventDefault();restore(historyIndex+1)}});
refreshLayers();snapshot();