const NS="http://www.w3.org/2000/svg",$=id=>document.getElementById(id);
const canvas=$("canvas"),objects=$("objects"),selectionLayer=$("selectionLayer"),stage=$("stage");
let tool="select",selected=null,drawing=null,start=null,action=null,zoom=1,docSize=512,snap=8;
let history=[],historyIndex=-1,restoring=false,saveTimer;
const mk=(tag,a={})=>{const e=document.createElementNS(NS,tag);Object.entries(a).forEach(([k,v])=>e.setAttribute(k,v));return e};
const pt=e=>{const p=canvas.createSVGPoint();p.x=e.clientX;p.y=e.clientY;return p.matrixTransform(canvas.getScreenCTM().inverse())};
const q=v=>$("snapToggle").checked?Math.round(v/snap)*snap:v;
function toast(s){$("toast").textContent=s;$("toast").classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>$("toast").classList.remove("show"),1300)}
function state(){return JSON.stringify({o:objects.innerHTML,b:$("artboard").getAttribute("fill"),s:docSize})}
function snapshot(){if(restoring)return;const s=state();if(history[historyIndex]===s)return;history=history.slice(0,historyIndex+1);history.push(s);historyIndex++;if(history.length>80){history.shift();historyIndex--}queueSave()}
function restore(i){if(i<0||i>=history.length)return;restoring=true;historyIndex=i;const s=JSON.parse(history[i]);objects.innerHTML=s.o;docSize=s.s||512;applySize();$("artboard").setAttribute("fill",s.b);$("background").value=s.b;$("backgroundHex").value=s.b;select(null);layers();restoring=false;queueSave()}
function queueSave(){clearTimeout(saveTimer);$("savedState").textContent="• salvando…";saveTimer=setTimeout(()=>{localStorage.setItem("iconStudioDocument",state());$("savedState").textContent="• salvo localmente"},250)}
function loadLocal(){try{const raw=localStorage.getItem("iconStudioDocument");if(!raw)return;const s=JSON.parse(raw);objects.innerHTML=s.o||"";docSize=s.s||512;applySize();$("artboard").setAttribute("fill",s.b||"#ffffff");$("background").value=s.b||"#ffffff";$("backgroundHex").value=s.b||"#ffffff"}catch{}}
function applySize(){canvas.setAttribute("viewBox",`0 0 ${docSize} ${docSize}`);$("artboard").setAttribute("width",docSize);$("artboard").setAttribute("height",docSize);$("preset").value=String(docSize);$("status").previousElementSibling.textContent=`${docSize} × ${docSize} px`;setZoom(zoom)}
function setTool(t){tool=t;document.querySelectorAll("[data-tool]").forEach(b=>b.classList.toggle("active",b.dataset.tool===t));$("status").textContent=t==="select"?"Selecionar":t;canvas.style.cursor=t==="select"?"default":"crosshair"}
function ensure(el){if(!el.id)el.id="obj_"+crypto.getRandomValues(new Uint32Array(1))[0];if(!el.dataset.name)el.dataset.name=({rect:"Retângulo",ellipse:"Elipse",line:"Linha",text:"Texto",polygon:"Estrela"}[el.tagName.toLowerCase()]||"Objeto")}
function style(el){el.setAttribute("fill",$("fill").value);el.setAttribute("stroke",$("stroke").value);el.setAttribute("stroke-width",$("strokeWidth").value);el.setAttribute("opacity",$("opacity").value/100);ensure(el)}
function box(el=selected){return el?el.getBBox():null}
function select(el){selected=el;selectionLayer.innerHTML="";if(el){ensure(el);drawSel();sync()}else clearInputs();layers()}
function drawSel(){selectionLayer.innerHTML="";if(!selected)return;const b=box(),pad=4;selectionLayer.append(mk("rect",{x:b.x-pad,y:b.y-pad,width:b.width+pad*2,height:b.height+pad*2,class:"selection-box"}));const hs=[[b.x-pad,b.y-pad,"nw"],[b.x+b.width+pad,b.y-pad,"ne"],[b.x+b.width+pad,b.y+b.height+pad,"se"],[b.x-pad,b.y+b.height+pad,"sw"]];hs.forEach(([x,y,n])=>selectionLayer.append(mk("circle",{cx:x,cy:y,r:5,class:"handle","data-handle":n})));const rx=b.x+b.width/2,ry=b.y-28;selectionLayer.append(mk("line",{x1:rx,y1:b.y-pad,x2:rx,y2:ry+5,class:"rotate-line"}));selectionLayer.append(mk("circle",{cx:rx,cy:ry,r:5,class:"handle rotate","data-handle":"rotate"}))}
function sync(){if(!selected)return;const b=box();$("posX").value=Math.round(b.x);$("posY").value=Math.round(b.y);$("sizeW").value=Math.max(1,Math.round(b.width));$("sizeH").value=Math.max(1,Math.round(b.height));$("rotation").value=+(selected.dataset.rotation||0);$("strokeWidth").value=selected.getAttribute("stroke-width")||0;$("strokeValue").value=$("strokeWidth").value;$("opacity").value=Math.round((selected.getAttribute("opacity")??1)*100);$("opacityValue").value=$("opacity").value+"%";const f=selected.getAttribute("fill"),s=selected.getAttribute("stroke");if(/^#[0-9a-f]{6}$/i.test(f||""))$("fill").value=f;if(/^#[0-9a-f]{6}$/i.test(s||""))$("stroke").value=s;if(selected.tagName==="rect"){$("radius").value=selected.getAttribute("rx")||0;$("radiusValue").value=$("radius").value}layers()}
function clearInputs(){["posX","posY","sizeW","sizeH","rotation"].forEach(i=>$(i).value="")}
function move(el,dx,dy){const t=el.tagName.toLowerCase();if(["rect","text"].includes(t)){el.setAttribute("x",(+el.getAttribute("x")||0)+dx);el.setAttribute("y",(+el.getAttribute("y")||0)+dy)}else if(t==="ellipse"){el.setAttribute("cx",(+el.getAttribute("cx")||0)+dx);el.setAttribute("cy",(+el.getAttribute("cy")||0)+dy)}else if(t==="line"){["x1","x2"].forEach(a=>el.setAttribute(a,+el.getAttribute(a)+dx));["y1","y2"].forEach(a=>el.setAttribute(a,+el.getAttribute(a)+dy))}else if(t==="polygon"){el.setAttribute("points",el.getAttribute("points").split(" ").map(p=>{let[x,y]=p.split(",").map(Number);return `${x+dx},${y+dy}`}).join(" "))}}
function scaleTo(el,nx,ny,nw,nh){const b=box(el),sx=nw/Math.max(.001,b.width),sy=nh/Math.max(.001,b.height),ox=b.x,oy=b.y;const t=el.tagName.toLowerCase();if(t==="rect"){el.setAttribute("x",nx);el.setAttribute("y",ny);el.setAttribute("width",nw);el.setAttribute("height",nh)}else if(t==="ellipse"){el.setAttribute("cx",nx+nw/2);el.setAttribute("cy",ny+nh/2);el.setAttribute("rx",nw/2);el.setAttribute("ry",nh/2)}else if(t==="line"){["x1","x2"].forEach(a=>el.setAttribute(a,nx+(+el.getAttribute(a)-ox)*sx));["y1","y2"].forEach(a=>el.setAttribute(a,ny+(+el.getAttribute(a)-oy)*sy))}else if(t==="polygon"){el.setAttribute("points",el.getAttribute("points").split(" ").map(p=>{let[x,y]=p.split(",").map(Number);return `${nx+(x-ox)*sx},${ny+(y-oy)*sy}`}).join(" "))}else if(t==="text"){const fs=parseFloat(el.getAttribute("font-size")||32);el.setAttribute("font-size",fs*Math.min(sx,sy));el.setAttribute("x",nx);el.setAttribute("y",ny+nh)}}
function rotate(el,deg){const b=box(el),cx=b.x+b.width/2,cy=b.y+b.height/2;el.dataset.rotation=deg;el.setAttribute("transform",`rotate(${deg} ${cx} ${cy})`)}
function layers(){const host=$("layers");host.innerHTML="";const arr=[...objects.children].reverse();if(!arr.length){host.innerHTML='<div class="empty">Nenhum objeto</div>';return}arr.forEach(el=>{ensure(el);const r=document.createElement("div");r.className="layer"+(el===selected?" active":"");r.innerHTML=`<span class="layer-icon">${({rect:"□",ellipse:"○",line:"╱",text:"T",polygon:"☆"}[el.tagName.toLowerCase()]||"◆")}</span><span>${el.dataset.name}</span><button class="layer-eye">${el.style.display==="none"?"○":"●"}</button>`;r.onclick=e=>{if(e.target.classList.contains("layer-eye")){el.style.display=el.style.display==="none"?"":"none";e.target.textContent=el.style.display==="none"?"○":"●";snapshot();return}select(el)};host.append(r)})}
function starPoints(cx,cy,r){let a=[];for(let i=0;i<10;i++){let rr=i%2?r*.45:r,ang=-Math.PI/2+i*Math.PI/5;a.push(`${cx+Math.cos(ang)*rr},${cy+Math.sin(ang)*rr}`)}return a.join(" ")}
canvas.onpointerdown=e=>{const p=pt(e),handle=e.target.dataset?.handle;if(handle&&selected){action={type:handle==="rotate"?"rotate":"resize",handle,start:p,b:box(),rot:+(selected.dataset.rotation||0)};canvas.setPointerCapture(e.pointerId);return}start={x:q(p.x),y:q(p.y)};if(tool==="select"){const target=e.target.closest("#objects > *");select(target||null);if(selected){action={type:"move",last:p};canvas.setPointerCapture(e.pointerId)}return}if(tool==="text"){const val=prompt("Texto:","LS");if(!val)return;drawing=mk("text",{x:start.x,y:start.y,"font-size":72,"font-family":"Inter,Arial,sans-serif","font-weight":"700"});style(drawing);drawing.textContent=val;objects.append(drawing);select(drawing);snapshot();setTool("select");return}let a=tool==="rect"?{x:start.x,y:start.y,width:1,height:1,rx:+$("radius").value}:tool==="ellipse"?{cx:start.x,cy:start.y,rx:1,ry:1}:tool==="line"?{x1:start.x,y1:start.y,x2:start.x,y2:start.y}:{points:starPoints(start.x,start.y,1)};drawing=mk(tool==="star"?"polygon":tool,a);style(drawing);if(tool==="line")drawing.setAttribute("fill","none");objects.append(drawing);canvas.setPointerCapture(e.pointerId)};
canvas.onpointermove=e=>{const p=pt(e);$("coords").textContent=`x ${Math.round(p.x)} · y ${Math.round(p.y)}`;if(action&&selected){if(action.type==="move"){let dx=p.x-action.last.x,dy=p.y-action.last.y;move(selected,dx,dy);action.last=p}else if(action.type==="resize"){const b=action.b,h=action.handle;let x=h.includes("w")?q(p.x):b.x,y=h.includes("n")?q(p.y):b.y,w=h.includes("w")?b.x+b.width-x:q(p.x)-b.x,hg=h.includes("n")?b.y+b.height-y:q(p.y)-b.y;if(w>2&&hg>2)scaleTo(selected,x,y,w,hg)}else{const b=action.b,cx=b.x+b.width/2,cy=b.y+b.height/2,deg=Math.atan2(p.y-cy,p.x-cx)*180/Math.PI+90;if(e.shiftKey)deg=Math.round(deg/15)*15;rotate(selected,Math.round(deg))}drawSel();sync();return}if(!drawing)return;const x=q(p.x),y=q(p.y),lx=Math.min(start.x,x),ly=Math.min(start.y,y),w=Math.abs(x-start.x),h=Math.abs(y-start.y);if(tool==="rect"){drawing.setAttribute("x",lx);drawing.setAttribute("y",ly);drawing.setAttribute("width",w);drawing.setAttribute("height",h)}else if(tool==="ellipse"){drawing.setAttribute("cx",(start.x+x)/2);drawing.setAttribute("cy",(start.y+y)/2);drawing.setAttribute("rx",w/2);drawing.setAttribute("ry",h/2)}else if(tool==="line"){drawing.setAttribute("x2",x);drawing.setAttribute("y2",y)}else drawing.setAttribute("points",starPoints(start.x,start.y,Math.hypot(x-start.x,y-start.y)))};
canvas.onpointerup=()=>{if(action){action=null;snapshot()}if(drawing){select(drawing);drawing=null;snapshot();setTool("select")}layers()};
document.querySelectorAll("[data-tool]").forEach(b=>b.onclick=()=>setTool(b.dataset.tool));
function del(){if(!selected)return;selected.remove();selected=null;selectionLayer.innerHTML="";layers();snapshot()}function dup(){if(!selected)return;const c=selected.cloneNode(true);c.id="";ensure(c);move(c,12,12);objects.append(c);select(c);snapshot()}
$("deleteBtn").onclick=del;$("duplicateBtn").onclick=dup;
$("fill").oninput=e=>{if(selected)selected.setAttribute("fill",e.target.value)};$("fill").onchange=snapshot;$("fillNone").onclick=()=>{if(selected){selected.setAttribute("fill","none");snapshot()}};
$("stroke").oninput=e=>{if(selected)selected.setAttribute("stroke",e.target.value)};$("stroke").onchange=snapshot;$("strokeNone").onclick=()=>{if(selected){selected.setAttribute("stroke","none");snapshot()}};
$("strokeWidth").oninput=e=>{$("strokeValue").value=e.target.value;if(selected)selected.setAttribute("stroke-width",e.target.value)};$("strokeWidth").onchange=snapshot;
$("opacity").oninput=e=>{$("opacityValue").value=e.target.value+"%";if(selected)selected.setAttribute("opacity",e.target.value/100)};$("opacity").onchange=snapshot;
$("radius").oninput=e=>{$("radiusValue").value=e.target.value;if(selected?.tagName==="rect")selected.setAttribute("rx",e.target.value)};$("radius").onchange=snapshot;
$("background").oninput=e=>{$("artboard").setAttribute("fill",e.target.value);$("backgroundHex").value=e.target.value.toUpperCase()};$("background").onchange=snapshot;$("backgroundHex").onchange=e=>{if(/^#[0-9a-f]{6}$/i.test(e.target.value)){$("background").value=e.target.value;$("artboard").setAttribute("fill",e.target.value);snapshot()}};
["posX","posY","sizeW","sizeH"].forEach(id=>$(id).onchange=()=>{if(!selected)return;const b=box(),x=+$("posX").value,y=+$("posY").value,w=Math.max(1,+$("sizeW").value),h=Math.max(1,+$("sizeH").value);scaleTo(selected,x,y,w,h);drawSel();snapshot()});$("rotation").onchange=e=>{if(selected){rotate(selected,+e.target.value);drawSel();snapshot()}};
function order(where){if(!selected)return;if(where==="front")objects.append(selected);if(where==="back")objects.prepend(selected);if(where==="up"&&selected.nextElementSibling)objects.insertBefore(selected.nextElementSibling,selected);if(where==="down"&&selected.previousElementSibling)objects.insertBefore(selected,selected.previousElementSibling);layers();snapshot()}$("frontBtn").onclick=()=>order("front");$("backBtn").onclick=()=>order("back");$("upBtn").onclick=()=>order("up");$("downBtn").onclick=()=>order("down");
$("centerH").onclick=()=>{if(selected){const b=box();move(selected,docSize/2-(b.x+b.width/2),0);drawSel();sync();snapshot()}};$("centerV").onclick=()=>{if(selected){const b=box();move(selected,0,docSize/2-(b.y+b.height/2));drawSel();sync();snapshot()}};
function flip(axis){if(!selected)return;const b=box(),cx=b.x+b.width/2,cy=b.y+b.height/2,rot=+(selected.dataset.rotation||0),s=axis==="h"?`translate(${2*cx} 0) scale(-1 1)`:`translate(0 ${2*cy}) scale(1 -1)`;selected.setAttribute("transform",s+(rot?` rotate(${rot} ${cx} ${cy})`:""));snapshot()}$("flipH").onclick=()=>flip("h");$("flipV").onclick=()=>flip("v");
function setZoom(z){zoom=Math.max(.2,Math.min(3,z));canvas.style.width=docSize*zoom+"px";canvas.style.height=docSize*zoom+"px";$("zoomLabel").textContent=Math.round(zoom*100)+"%"}$("zoomIn").onclick=()=>setZoom(zoom+.25);$("zoomOut").onclick=()=>setZoom(zoom-.25);$("zoomFit").onclick=()=>{const r=stage.getBoundingClientRect();setZoom(Math.min((r.width-100)/docSize,(r.height-100)/docSize,1.5))};$("gridToggle").onchange=e=>stage.classList.toggle("no-grid",!e.target.checked);
$("preset").onchange=e=>{docSize=+e.target.value;applySize();snapshot()};
$("undoBtn").onclick=()=>restore(historyIndex-1);$("redoBtn").onclick=()=>restore(historyIndex+1);
$("newBtn").onclick=()=>{if(objects.children.length&&!confirm("Limpar o desenho atual?"))return;objects.innerHTML="";docSize=512;applySize();$("artboard").setAttribute("fill","#ffffff");$("background").value="#ffffff";$("backgroundHex").value="#FFFFFF";select(null);snapshot()};
$("openBtn").onclick=()=>$("fileInput").click();$("fileInput").onchange=async e=>{const text=await e.target.files[0]?.text();if(!text)return;try{const doc=new DOMParser().parseFromString(text,"image/svg+xml"),svg=doc.documentElement;if(svg.tagName.toLowerCase()!=="svg")throw 0;const vb=(svg.getAttribute("viewBox")||"0 0 512 512").split(/\s+/).map(Number);if(vb[2]===vb[3]&&vb[2]>0){docSize=vb[2];applySize()}objects.innerHTML="";[...svg.children].forEach(n=>{if(n.tagName.toLowerCase()==="rect"&&+n.getAttribute("width")===docSize&&+n.getAttribute("height")===docSize&&!objects.children.length){const f=n.getAttribute("fill");if(f&&f!=="none"){$("artboard").setAttribute("fill",f);return}}objects.append(document.importNode(n,true))});[...objects.children].forEach(ensure);select(null);layers();snapshot();toast("SVG importado")}catch{toast("SVG inválido")}e.target.value=""};
function clean(){const c=canvas.cloneNode(true);c.querySelector("#selectionLayer")?.remove();c.removeAttribute("style");c.setAttribute("width",docSize);c.setAttribute("height",docSize);return new XMLSerializer().serializeToString(c)}function download(blob,name){const a=document.createElement("a"),u=URL.createObjectURL(blob);a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
$("exportSvg").onclick=()=>{download(new Blob([clean()],{type:"image/svg+xml"}),"icon.svg");toast("SVG exportado")};$("exportPng").onclick=()=>{const im=new Image(),u=URL.createObjectURL(new Blob([clean()],{type:"image/svg+xml"}));im.onload=()=>{const c=document.createElement("canvas");c.width=c.height=docSize;c.getContext("2d").drawImage(im,0,0);c.toBlob(b=>download(b,"icon.png"),"image/png");URL.revokeObjectURL(u);toast("PNG exportado")};im.src=u};
window.onkeydown=e=>{if(["INPUT","SELECT","TEXTAREA"].includes(document.activeElement.tagName))return;const k=e.key.toLowerCase(),mod=e.ctrlKey||e.metaKey;if(mod&&k==="z"){e.preventDefault();restore(historyIndex-(e.shiftKey?-1:1));return}if(mod&&k==="y"){e.preventDefault();restore(historyIndex+1);return}if(mod&&k==="d"){e.preventDefault();dup();return}if((e.key==="Delete"||e.key==="Backspace")&&selected){e.preventDefault();del();return}if(["v","r","e","l","t"].includes(k))setTool({v:"select",r:"rect",e:"ellipse",l:"line",t:"text"}[k]);if(selected&&["arrowleft","arrowright","arrowup","arrowdown"].includes(k)){e.preventDefault();let d=e.shiftKey?10:1;move(selected,k==="arrowleft"?-d:k==="arrowright"?d:0,k==="arrowup"?-d:k==="arrowdown"?d:0);drawSel();sync();snapshot()}};
loadLocal();[...objects.children].forEach(ensure);layers();snapshot();setTimeout(()=>$("zoomFit").click(),0);