const NS="http://www.w3.org/2000/svg",$=id=>document.getElementById(id);
const canvas=$("canvas"),objects=$("objects"),selectionLayer=$("selectionLayer"),stage=$("stage");
let tool="select",selected=null,drawing=null,start=null,action=null,zoom=1,docSize=512,snap=8,transparent=true;
let history=[],historyIndex=-1,restoring=false,saveTimer,clipboard=null;
const mk=(tag,a={})=>{const e=document.createElementNS(NS,tag);Object.entries(a).forEach(([k,v])=>e.setAttribute(k,v));return e};
const pt=e=>{const p=canvas.createSVGPoint();p.x=e.clientX;p.y=e.clientY;return p.matrixTransform(canvas.getScreenCTM().inverse())};
const q=v=>$("snapToggle").checked?Math.round(v/snap)*snap:v;
function toast(s){$("toast").textContent=s;$("toast").classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>$("toast").classList.remove("show"),1300)}
function state(){return JSON.stringify({o:objects.innerHTML,d:canvas.querySelector("defs").innerHTML,b:$("artboard").getAttribute("fill"),s:docSize,t:transparent})}
function snapshot(){if(restoring)return;const s=state();if(history[historyIndex]===s)return;history=history.slice(0,historyIndex+1);history.push(s);historyIndex++;if(history.length>80){history.shift();historyIndex--}queueSave()}
function restore(i){if(i<0||i>=history.length)return;restoring=true;historyIndex=i;const s=JSON.parse(history[i]);objects.innerHTML=s.o;canvas.querySelector("defs").innerHTML=s.d||canvas.querySelector("defs").innerHTML;docSize=s.s||512;transparent=s.t!==undefined?s.t:s.b==="none";applySize();$("artboard").setAttribute("fill",transparent?"none":(s.b||"#ffffff"));if(s.b&&s.b!=="none"){$("background").value=s.b;$("backgroundHex").value=s.b}syncBackgroundUI();select(null);layers();restoring=false;queueSave()}
function queueSave(){clearTimeout(saveTimer);$("savedState").textContent="• salvando…";saveTimer=setTimeout(()=>{localStorage.setItem("iconStudioDocument",state());$("savedState").textContent="• salvo localmente"},250)}
function loadLocal(){try{const raw=localStorage.getItem("iconStudioDocument");if(!raw)return;const s=JSON.parse(raw);objects.innerHTML=s.o||"";if(s.d)canvas.querySelector("defs").innerHTML=s.d;docSize=s.s||512;transparent=s.t!==undefined?s.t:s.b==="none";applySize();const bg=s.b&&s.b!=="none"?s.b:"#ffffff";$("artboard").setAttribute("fill",transparent?"none":bg);$("background").value=bg;$("backgroundHex").value=bg;syncBackgroundUI()}catch{}}
function applySize(){canvas.setAttribute("viewBox",`0 0 ${docSize} ${docSize}`);$("artboard").setAttribute("width",docSize);$("artboard").setAttribute("height",docSize);$("checkerboard").setAttribute("width",docSize);$("checkerboard").setAttribute("height",docSize);$("preset").value=String(docSize);$("status").previousElementSibling.textContent=`${docSize} × ${docSize} px`;setZoom(zoom)}
const shapeNames={triangle:["△","Triângulo"],diamond:["◇","Losango"],pentagon:["⬠","Pentágono"],hexagon:["⬡","Hexágono"],star:["☆","Estrela"],heart:["♡","Coração"],arrow:["➜","Seta"],cross:["＋","Cruz"],ring:["◎","Anel"],polygon:["⬢","Polígono"]};function setTool(t){tool=t;document.querySelectorAll("[data-tool]").forEach(b=>b.classList.toggle("active",b.dataset.tool===t));const isShape=!!shapeNames[t];$("shapeTrigger")?.classList.toggle("active",isShape);document.querySelectorAll("[data-shape]").forEach(b=>b.classList.toggle("active",b.dataset.shape===t));$("status").textContent=t==="select"?"Selecionar":(shapeNames[t]?.[1]||t);canvas.style.cursor=t==="select"?"default":"crosshair"}
function ensure(el){if(!el.id)el.id="obj_"+crypto.getRandomValues(new Uint32Array(1))[0];if(!el.dataset.name)el.dataset.name=({rect:"Retângulo",ellipse:"Elipse",line:"Linha",text:"Texto",polygon:"Forma",path:"Desenho"}[el.tagName.toLowerCase()]||"Objeto")}
function style(el){el.setAttribute("fill",$("fill").value);el.setAttribute("stroke",$("stroke").value);el.setAttribute("stroke-width",$("strokeWidth").value);el.setAttribute("stroke-linecap",$("lineCap").value);el.setAttribute("stroke-linejoin","round");el.setAttribute("stroke-dasharray",$("lineStyle").value);el.setAttribute("opacity",$("opacity").value/100);ensure(el)}
function box(el=selected){return el?el.getBBox():null}
function select(el){selected=el;selectionLayer.innerHTML="";if(el){ensure(el);drawSel();sync()}else clearInputs();layers()}
function drawSel(){selectionLayer.innerHTML="";if(!selected)return;const b=box(),pad=4;selectionLayer.append(mk("rect",{x:b.x-pad,y:b.y-pad,width:b.width+pad*2,height:b.height+pad*2,class:"selection-box"}));const hs=[[b.x-pad,b.y-pad,"nw"],[b.x+b.width+pad,b.y-pad,"ne"],[b.x+b.width+pad,b.y+b.height+pad,"se"],[b.x-pad,b.y+b.height+pad,"sw"]];hs.forEach(([x,y,n])=>selectionLayer.append(mk("circle",{cx:x,cy:y,r:5,class:"handle","data-handle":n})));const rx=b.x+b.width/2,ry=b.y-28;selectionLayer.append(mk("line",{x1:rx,y1:b.y-pad,x2:rx,y2:ry+5,class:"rotate-line"}));selectionLayer.append(mk("circle",{cx:rx,cy:ry,r:5,class:"handle rotate","data-handle":"rotate"}))}
function sync(){if(!selected)return;const b=box();$("posX").value=Math.round(b.x);$("posY").value=Math.round(b.y);$("sizeW").value=Math.max(1,Math.round(b.width));$("sizeH").value=Math.max(1,Math.round(b.height));$("rotation").value=+(selected.dataset.rotation||0);$("strokeWidth").value=selected.getAttribute("stroke-width")||0;$("strokeValue").value=$("strokeWidth").value;$("opacity").value=Math.round((selected.getAttribute("opacity")??1)*100);$("opacityValue").value=$("opacity").value+"%";$("blur").value=selected.dataset.blur||0;$("blurValue").value=$("blur").value;const f=selected.getAttribute("fill"),s=selected.getAttribute("stroke");if(/^#[0-9a-f]{6}$/i.test(f||"")){$("fill").value=f;$("fillMode").value="solid"}else if(/^url\(#grad_/.test(f||"")){const g=canvas.querySelector(f.match(/#([^)]+)/)?.[0]);if(g){$("fillMode").value="linear";const stops=g.querySelectorAll("stop");if(stops[0])$("fill").value=stops[0].getAttribute("stop-color");if(stops[1])$("gradientColor").value=stops[1].getAttribute("stop-color");$("gradientAngle").value=selected.dataset.gradientAngle||0;$("gradientAngleValue").value=$("gradientAngle").value+"°"}}$("gradientRow").classList.toggle("disabled",$("fillMode").value!=="linear");if(/^#[0-9a-f]{6}$/i.test(s||""))$("stroke").value=s;if(selected.tagName==="rect"){$("radius").value=selected.getAttribute("rx")||0;$("radiusValue").value=$("radius").value}layers()}
function clearInputs(){["posX","posY","sizeW","sizeH","rotation"].forEach(i=>$(i).value="")}
function move(el,dx,dy){const t=el.tagName.toLowerCase();if(["rect","text"].includes(t)){el.setAttribute("x",(+el.getAttribute("x")||0)+dx);el.setAttribute("y",(+el.getAttribute("y")||0)+dy)}else if(t==="ellipse"){el.setAttribute("cx",(+el.getAttribute("cx")||0)+dx);el.setAttribute("cy",(+el.getAttribute("cy")||0)+dy)}else if(t==="line"){["x1","x2"].forEach(a=>el.setAttribute(a,+el.getAttribute(a)+dx));["y1","y2"].forEach(a=>el.setAttribute(a,+el.getAttribute(a)+dy))}else if(t==="polygon"){el.setAttribute("points",el.getAttribute("points").split(" ").map(p=>{let[x,y]=p.split(",").map(Number);return `${x+dx},${y+dy}`}).join(" "))}else if(t==="path"){el.setAttribute("transform",`translate(${(+el.dataset.tx||0)+dx} ${( +el.dataset.ty||0)+dy})`);el.dataset.tx=(+el.dataset.tx||0)+dx;el.dataset.ty=(+el.dataset.ty||0)+dy}}
function scaleTo(el,nx,ny,nw,nh){const b=box(el),sx=nw/Math.max(.001,b.width),sy=nh/Math.max(.001,b.height),ox=b.x,oy=b.y;const t=el.tagName.toLowerCase();if(t==="rect"){el.setAttribute("x",nx);el.setAttribute("y",ny);el.setAttribute("width",nw);el.setAttribute("height",nh)}else if(t==="ellipse"){el.setAttribute("cx",nx+nw/2);el.setAttribute("cy",ny+nh/2);el.setAttribute("rx",nw/2);el.setAttribute("ry",nh/2)}else if(t==="line"){["x1","x2"].forEach(a=>el.setAttribute(a,nx+(+el.getAttribute(a)-ox)*sx));["y1","y2"].forEach(a=>el.setAttribute(a,ny+(+el.getAttribute(a)-oy)*sy))}else if(t==="polygon"){el.setAttribute("points",el.getAttribute("points").split(" ").map(p=>{let[x,y]=p.split(",").map(Number);return `${nx+(x-ox)*sx},${ny+(y-oy)*sy}`}).join(" "))}else if(t==="text"){const fs=parseFloat(el.getAttribute("font-size")||32);el.setAttribute("font-size",fs*Math.min(sx,sy));el.setAttribute("x",nx);el.setAttribute("y",ny+nh)}else if(t==="path"){el.setAttribute("transform",`translate(${nx-ox} ${ny-oy}) scale(${sx} ${sy})`)}}
function applyTransform(el){const b=box(el),cx=b.x+b.width/2,cy=b.y+b.height/2,deg=+(el.dataset.rotation||0),fx=el.dataset.flipH==="1"?-1:1,fy=el.dataset.flipV==="1"?-1:1;el.setAttribute("transform",`translate(${cx} ${cy}) rotate(${deg}) scale(${fx} ${fy}) translate(${-cx} ${-cy})`)}function rotate(el,deg){el.dataset.rotation=deg;applyTransform(el)}
function layers(){const host=$("layers");host.innerHTML="";const arr=[...objects.children].reverse();if(!arr.length){host.innerHTML='<div class="empty">Nenhum objeto</div>';return}arr.forEach(el=>{ensure(el);const r=document.createElement("div");r.className="layer"+(el===selected?" active":"")+(el.dataset.locked==="1"?" locked":"");r.innerHTML=`<span class="layer-icon">${el.dataset.locked==="1"?"🔒":({rect:"□",ellipse:"○",line:"╱",text:"T",polygon:"☆"}[el.tagName.toLowerCase()]||"◆")}</span><span>${el.dataset.name}</span><button class="layer-eye">${el.style.display==="none"?"○":"●"}</button>`;r.onclick=e=>{if(e.target.classList.contains("layer-eye")){el.style.display=el.style.display==="none"?"":"none";e.target.textContent=el.style.display==="none"?"○":"●";snapshot();return}select(el)};host.append(r)})}
function regularPoints(cx,cy,r,n,offset=-Math.PI/2){let a=[];for(let i=0;i<n;i++){let ang=offset+i*Math.PI*2/n;a.push(`${cx+Math.cos(ang)*r},${cy+Math.sin(ang)*r}`)}return a.join(" ")}
function starPoints(cx,cy,r){let a=[];for(let i=0;i<10;i++){let rr=i%2?r*.45:r,ang=-Math.PI/2+i*Math.PI/5;a.push(`${cx+Math.cos(ang)*rr},${cy+Math.sin(ang)*rr}`)}return a.join(" ")}
function shapePoints(kind,cx,cy,r){if(kind==="triangle")return regularPoints(cx,cy,r,3);if(kind==="diamond")return regularPoints(cx,cy,r,4,0);if(kind==="pentagon")return regularPoints(cx,cy,r,5);if(kind==="hexagon")return regularPoints(cx,cy,r,6,0);if(kind==="star")return starPoints(cx,cy,r);if(kind==="polygon")return regularPoints(cx,cy,r,Math.max(3,Math.min(24,+$("polygonSides").value||6)));if(kind==="arrow")return [[cx-r,cy-r*.32],[cx+r*.15,cy-r*.32],[cx+r*.15,cy-r*.7],[cx+r,cy],[cx+r*.15,cy+r*.7],[cx+r*.15,cy+r*.32],[cx-r,cy+r*.32]].map(p=>p.join(",")).join(" ");if(kind==="cross")return [[cx-r*.3,cy-r],[cx+r*.3,cy-r],[cx+r*.3,cy-r*.3],[cx+r,cy-r*.3],[cx+r,cy+r*.3],[cx+r*.3,cy+r*.3],[cx+r*.3,cy+r],[cx-r*.3,cy+r],[cx-r*.3,cy+r*.3],[cx-r,cy+r*.3],[cx-r,cy-r*.3],[cx-r*.3,cy-r*.3]].map(p=>p.join(",")).join(" ");return ""}
function heartPath(cx,cy,r){return `M ${cx} ${cy+r*.78} C ${cx-r*1.2} ${cy}, ${cx-r*.72} ${cy-r*.85}, ${cx} ${cy-r*.25} C ${cx+r*.72} ${cy-r*.85}, ${cx+r*1.2} ${cy}, ${cx} ${cy+r*.78} Z`}
canvas.onpointerdown=e=>{const p=pt(e),handle=e.target.dataset?.handle;if(handle&&selected){action={type:handle==="rotate"?"rotate":"resize",handle,start:p,b:box(),rot:+(selected.dataset.rotation||0)};canvas.setPointerCapture(e.pointerId);return}start={x:q(p.x),y:q(p.y)};if(tool==="select"){const target=e.target.closest("#objects > *");select(target||null);if(selected&&selected.dataset.locked!=="1"){action={type:"move",last:p};canvas.setPointerCapture(e.pointerId)}return}if(tool==="eyedropper"){const target=e.target.closest("#objects > *");if(target){const col=target.getAttribute("fill");if(/^#[0-9a-f]{6}$/i.test(col||"")){$("fill").value=col;toast("Cor capturada")}}setTool("select");return}if(tool==="text"){const val=prompt("Texto:","LS");if(!val)return;drawing=mk("text",{x:start.x,y:start.y,"font-size":$("fontSize").value,"font-family":$("fontFamily").value,"font-weight":$("fontWeight").value});style(drawing);drawing.textContent=val;objects.append(drawing);select(drawing);snapshot();setTool("select");return}if(tool==="freehand"){drawing=mk("path",{d:`M ${start.x} ${start.y}`});style(drawing);drawing.setAttribute("fill","none");if(drawing.getAttribute("stroke")==="none")drawing.setAttribute("stroke",$("fill").value||"#69a7ff");if((+drawing.getAttribute("stroke-width")||0)<1){drawing.setAttribute("stroke-width","4");$("strokeWidth").value=4;$("strokeValue").value=4}drawing.setAttribute("stroke-linecap","round");drawing.setAttribute("stroke-linejoin","round");drawing.dataset.name="Desenho livre";objects.append(drawing);canvas.setPointerCapture(e.pointerId);return}let poly=["triangle","diamond","pentagon","hexagon","star","arrow","cross","polygon"].includes(tool),a=tool==="rect"?{x:start.x,y:start.y,width:1,height:1,rx:+$("radius").value}:tool==="ellipse"||tool==="ring"?{cx:start.x,cy:start.y,rx:1,ry:1}:tool==="line"?{x1:start.x,y1:start.y,x2:start.x,y2:start.y}:tool==="heart"?{d:heartPath(start.x,start.y,1)}:{points:shapePoints(tool,start.x,start.y,1)};drawing=mk(poly?"polygon":tool==="heart"?"path":tool==="ring"?"ellipse":tool,a);style(drawing);drawing.dataset.name=({triangle:"Triângulo",diamond:"Losango",pentagon:"Pentágono",hexagon:"Hexágono",star:"Estrela",heart:"Coração",arrow:"Seta",cross:"Cruz",ring:"Anel",polygon:"Polígono"}[tool]||drawing.dataset.name);if(tool==="line"||tool==="ring"){drawing.setAttribute("fill","none");if(tool==="ring"&&+drawing.getAttribute("stroke-width")===0)drawing.setAttribute("stroke-width",12)}objects.append(drawing);canvas.setPointerCapture(e.pointerId)};
canvas.onpointermove=e=>{const p=pt(e);$("coords").textContent=`x ${Math.round(p.x)} · y ${Math.round(p.y)}`;if(action&&selected){if(action.type==="move"){let dx=p.x-action.last.x,dy=p.y-action.last.y;move(selected,dx,dy);action.last=p}else if(action.type==="resize"){const b=action.b,h=action.handle;let x=h.includes("w")?q(p.x):b.x,y=h.includes("n")?q(p.y):b.y,w=h.includes("w")?b.x+b.width-x:q(p.x)-b.x,hg=h.includes("n")?b.y+b.height-y:q(p.y)-b.y;if(w>2&&hg>2)scaleTo(selected,x,y,w,hg)}else{const b=action.b,cx=b.x+b.width/2,cy=b.y+b.height/2,deg=Math.atan2(p.y-cy,p.x-cx)*180/Math.PI+90;if(e.shiftKey)deg=Math.round(deg/15)*15;rotate(selected,Math.round(deg))}drawSel();sync();return}if(!drawing)return;if(tool==="freehand"){drawing.setAttribute("d",drawing.getAttribute("d")+` L ${p.x} ${p.y}`);return}const x=q(p.x),y=q(p.y),lx=Math.min(start.x,x),ly=Math.min(start.y,y),w=Math.abs(x-start.x),h=Math.abs(y-start.y);if(tool==="rect"){drawing.setAttribute("x",lx);drawing.setAttribute("y",ly);drawing.setAttribute("width",w);drawing.setAttribute("height",h)}else if(tool==="ellipse"){drawing.setAttribute("cx",(start.x+x)/2);drawing.setAttribute("cy",(start.y+y)/2);drawing.setAttribute("rx",w/2);drawing.setAttribute("ry",h/2)}else if(tool==="line"){drawing.setAttribute("x2",x);drawing.setAttribute("y2",y)}else if(tool==="heart"){drawing.setAttribute("d",heartPath(start.x,start.y,Math.hypot(x-start.x,y-start.y)))}else if(tool==="ring"){drawing.setAttribute("cx",(start.x+x)/2);drawing.setAttribute("cy",(start.y+y)/2);drawing.setAttribute("rx",w/2);drawing.setAttribute("ry",h/2)}else drawing.setAttribute("points",shapePoints(tool,start.x,start.y,Math.hypot(x-start.x,y-start.y)))};
canvas.onpointerup=()=>{if(action){action=null;snapshot()}if(drawing){select(drawing);drawing=null;snapshot();setTool("select")}layers()};
document.querySelectorAll("[data-tool]").forEach(b=>b.onclick=()=>setTool(b.dataset.tool));$("shapeTrigger").onclick=e=>{e.stopPropagation();$("shapePopover").classList.toggle("open")};document.querySelectorAll("[data-shape]").forEach(b=>b.onclick=e=>{e.stopPropagation();const t=b.dataset.shape,set=shapeNames[t];$("shapeIcon").textContent=set[0];$("shapeLabel").textContent=set[1];$("shapePopover").classList.remove("open");setTool(t)});document.addEventListener("pointerdown",e=>{if(!e.target.closest(".shape-picker"))$("shapePopover")?.classList.remove("open")});
function del(){if(!selected)return;selected.remove();selected=null;selectionLayer.innerHTML="";layers();snapshot()}function dup(){if(!selected)return;const c=selected.cloneNode(true);c.id="";ensure(c);move(c,12,12);objects.append(c);select(c);snapshot()}
$("deleteBtn").onclick=del;$("duplicateBtn").onclick=dup;
$("fill").oninput=e=>{if(!selected)return;if($("fillMode").value==="linear")applyGradient(false);else selected.setAttribute("fill",e.target.value)};$("fill").onchange=()=>{if(selected&&$("fillMode").value==="linear")applyGradient(true);else snapshot()};$("fillNone").onclick=()=>{if(selected){selected.setAttribute("fill","none");snapshot()}};
$("stroke").oninput=e=>{if(selected)selected.setAttribute("stroke",e.target.value)};$("stroke").onchange=snapshot;$("strokeNone").onclick=()=>{if(selected){selected.setAttribute("stroke","none");snapshot()}};
$("strokeWidth").oninput=e=>{$("strokeValue").value=e.target.value;if(selected)selected.setAttribute("stroke-width",e.target.value)};$("strokeWidth").onchange=snapshot;
$("opacity").oninput=e=>{$("opacityValue").value=e.target.value+"%";if(selected)selected.setAttribute("opacity",e.target.value/100)};$("opacity").onchange=snapshot;$("blur").oninput=e=>{$("blurValue").value=e.target.value;if(selected)applyBlur(false)};$("blur").onchange=()=>{if(selected)applyBlur(true)};
$("radius").oninput=e=>{$("radiusValue").value=e.target.value;if(selected?.tagName==="rect")selected.setAttribute("rx",e.target.value)};$("radius").onchange=snapshot;$("fillMode").onchange=()=>{const on=$("fillMode").value==="linear";$("gradientRow").classList.toggle("disabled",!on);applyGradient(true)};$("gradientColor").oninput=()=>{if($("fillMode").value==="linear")applyGradient(false)};$("gradientColor").onchange=()=>{if($("fillMode").value==="linear")applyGradient(true)};$("gradientAngle").oninput=e=>{$("gradientAngleValue").value=e.target.value+"°";if($("fillMode").value==="linear")applyGradient(false)};$("gradientAngle").onchange=()=>{if($("fillMode").value==="linear")applyGradient(true)};$("lineStyle").onchange=e=>{if(selected){selected.setAttribute("stroke-dasharray",e.target.value);snapshot()}};$("lineCap").onchange=e=>{if(selected){selected.setAttribute("stroke-linecap",e.target.value);snapshot()}};$("swapColors").onclick=()=>{const a=$("fill").value,b=$("stroke").value;$("fill").value=b;$("stroke").value=a;if(selected){selected.setAttribute("fill",b);selected.setAttribute("stroke",a);snapshot()}};$("fontFamily").onchange=e=>{if(selected?.tagName==="text"){selected.setAttribute("font-family",e.target.value);snapshot()}};$("fontSize").onchange=e=>{if(selected?.tagName==="text"){selected.setAttribute("font-size",e.target.value);drawSel();snapshot()}};$("fontWeight").onchange=e=>{if(selected?.tagName==="text"){selected.setAttribute("font-weight",e.target.value);snapshot()}};$("editText").onclick=()=>{if(selected?.tagName!=="text")return toast("Selecione um texto");const v=prompt("Texto:",selected.textContent);if(v!==null){selected.textContent=v;drawSel();snapshot()}};
function applyBlur(commit=false){if(!selected)return toast("Selecione um objeto primeiro");const amount=Math.max(0,+$("blur").value||0),defs=canvas.querySelector("defs"),id="blur_"+selected.id,old=defs.querySelector("#"+id);$("blurValue").value=amount;selected.dataset.blur=amount;if(amount<=0){selected.removeAttribute("filter");old?.remove();if(commit)snapshot();return}const filter=old||mk("filter",{id,x:"-50%",y:"-50%",width:"200%",height:"200%","color-interpolation-filters":"sRGB"});let gaussian=filter.querySelector("feGaussianBlur");if(!gaussian){gaussian=mk("feGaussianBlur",{in:"SourceGraphic",edgeMode:"duplicate"});filter.append(gaussian)}gaussian.setAttribute("stdDeviation",amount);if(!old)defs.append(filter);selected.setAttribute("filter","url(#"+id+")");if(commit)snapshot()}
function applyGradient(commit=false){if(!selected)return toast("Selecione uma forma primeiro");let defs=canvas.querySelector("defs"),id="grad_"+selected.id,old=defs.querySelector("#"+id);if($("fillMode").value!=="linear"){selected.setAttribute("fill",$("fill").value);selected.dataset.fillMode="solid";if(commit)snapshot();return}const a=+$("gradientAngle").value*Math.PI/180,x=Math.cos(a),y=Math.sin(a),g=old||mk("linearGradient",{id});g.setAttribute("x1",(50-x*50)+"%");g.setAttribute("y1",(50-y*50)+"%");g.setAttribute("x2",(50+x*50)+"%");g.setAttribute("y2",(50+y*50)+"%");g.innerHTML="";g.append(mk("stop",{offset:"0%","stop-color":$("fill").value}),mk("stop",{offset:"100%","stop-color":$("gradientColor").value}));if(!old)defs.append(g);selected.setAttribute("fill","url(#"+id+")");selected.dataset.fillMode="linear";selected.dataset.gradientAngle=$("gradientAngle").value;if(commit)snapshot()}
function copySelection(){if(selected){clipboard=selected.cloneNode(true);toast("Copiado")}}
function pasteSelection(){if(!clipboard)return toast("Nada para colar");const n=clipboard.cloneNode(true);n.id="";ensure(n);move(n,16,16);objects.append(n);select(n);snapshot();toast("Colado")}
function lockSelection(){if(!selected)return;selected.dataset.locked=selected.dataset.locked==="1"?"0":"1";$("lockBtn").textContent=selected.dataset.locked==="1"?"Desbloquear":"Bloquear";layers();snapshot()}
function syncBackgroundUI(){$("transparentBtn").classList.toggle("active",transparent);$("transparentBtn").textContent=transparent?"▧ Transparente":"■ Cor sólida";$("backgroundColorRow").classList.toggle("disabled",transparent);$("artboard").setAttribute("fill",transparent?"none":$("background").value)}$("transparentBtn").onclick=()=>{transparent=!transparent;syncBackgroundUI();snapshot()};$("background").oninput=e=>{if(!transparent)$("artboard").setAttribute("fill",e.target.value);$("backgroundHex").value=e.target.value.toUpperCase()};$("background").onchange=snapshot;$("backgroundHex").onchange=e=>{if(/^#[0-9a-f]{6}$/i.test(e.target.value)){$("background").value=e.target.value;if(!transparent)$("artboard").setAttribute("fill",e.target.value);snapshot()}};
["posX","posY","sizeW","sizeH"].forEach(id=>$(id).onchange=()=>{if(!selected)return;const b=box(),x=+$("posX").value,y=+$("posY").value,w=Math.max(1,+$("sizeW").value),h=Math.max(1,+$("sizeH").value);scaleTo(selected,x,y,w,h);drawSel();snapshot()});$("rotation").onchange=e=>{if(selected){rotate(selected,+e.target.value);drawSel();snapshot()}};
function order(where){if(!selected)return;if(where==="front")objects.append(selected);if(where==="back")objects.prepend(selected);if(where==="up"&&selected.nextElementSibling)objects.insertBefore(selected.nextElementSibling,selected);if(where==="down"&&selected.previousElementSibling)objects.insertBefore(selected,selected.previousElementSibling);layers();snapshot()}$("frontBtn").onclick=()=>order("front");$("backBtn").onclick=()=>order("back");$("upBtn").onclick=()=>order("up");$("downBtn").onclick=()=>order("down");
$("centerH").onclick=()=>{if(selected){const b=box();move(selected,docSize/2-(b.x+b.width/2),0);drawSel();sync();snapshot()}};$("centerV").onclick=()=>{if(selected){const b=box();move(selected,0,docSize/2-(b.y+b.height/2));drawSel();sync();snapshot()}};function align(edge){if(!selected)return;const b=box();if(edge==="left")move(selected,-b.x,0);if(edge==="right")move(selected,docSize-(b.x+b.width),0);if(edge==="top")move(selected,0,-b.y);if(edge==="bottom")move(selected,0,docSize-(b.y+b.height));drawSel();sync();snapshot()}$("alignLeft").onclick=()=>align("left");$("alignRight").onclick=()=>align("right");$("alignTop").onclick=()=>align("top");$("alignBottom").onclick=()=>align("bottom");$("copyBtn").onclick=copySelection;$("pasteBtn").onclick=pasteSelection;$("lockBtn").onclick=lockSelection;
function flip(axis){if(!selected)return;if(axis==="h")selected.dataset.flipH=selected.dataset.flipH==="1"?"0":"1";else selected.dataset.flipV=selected.dataset.flipV==="1"?"0":"1";applyTransform(selected);drawSel();snapshot()}$("flipH").onclick=()=>flip("h");$("flipV").onclick=()=>flip("v");
function setZoom(z){zoom=Math.max(.2,Math.min(3,z));canvas.style.width=docSize*zoom+"px";canvas.style.height=docSize*zoom+"px";$("zoomLabel").textContent=Math.round(zoom*100)+"%"}$("zoomIn").onclick=()=>setZoom(zoom+.25);$("zoomOut").onclick=()=>setZoom(zoom-.25);$("zoomFit").onclick=()=>{const r=stage.getBoundingClientRect();setZoom(Math.min((r.width-100)/docSize,(r.height-100)/docSize,1.5))};$("gridToggle").onchange=e=>stage.classList.toggle("no-grid",!e.target.checked);
$("preset").onchange=e=>{docSize=+e.target.value;applySize();snapshot()};
$("undoBtn").onclick=()=>restore(historyIndex-1);$("redoBtn").onclick=()=>restore(historyIndex+1);
$("newBtn").onclick=()=>{if(objects.children.length&&!confirm("Limpar o desenho atual?"))return;objects.innerHTML="";docSize=512;transparent=true;applySize();$("background").value="#ffffff";$("backgroundHex").value="#FFFFFF";syncBackgroundUI();select(null);snapshot()};
$("openBtn").onclick=()=>$("fileInput").click();$("fileInput").onchange=async e=>{const text=await e.target.files[0]?.text();if(!text)return;try{const doc=new DOMParser().parseFromString(text,"image/svg+xml"),svg=doc.documentElement;if(svg.tagName.toLowerCase()!=="svg")throw 0;const vb=(svg.getAttribute("viewBox")||"0 0 512 512").split(/\s+/).map(Number);if(vb[2]===vb[3]&&vb[2]>0){docSize=vb[2];applySize()}objects.innerHTML="";[...svg.children].forEach(n=>{if(n.tagName.toLowerCase()==="rect"&&+n.getAttribute("width")===docSize&&+n.getAttribute("height")===docSize&&!objects.children.length){const f=n.getAttribute("fill");if(f&&f!=="none"){transparent=false;$("background").value=f;$("backgroundHex").value=f;$("artboard").setAttribute("fill",f);syncBackgroundUI();return}}objects.append(document.importNode(n,true))});[...objects.children].forEach(ensure);select(null);layers();snapshot();toast("SVG importado")}catch{toast("SVG inválido")}e.target.value=""};
function clean(){const c=canvas.cloneNode(true);c.querySelector("#selectionLayer")?.remove();c.querySelector("#checkerboard")?.remove();c.querySelector("#checker")?.remove();if(!c.querySelector("defs")?.children.length)c.querySelector("defs")?.remove();if(transparent)c.querySelector("#artboard")?.remove();c.removeAttribute("style");c.setAttribute("width",docSize);c.setAttribute("height",docSize);return new XMLSerializer().serializeToString(c)}function download(blob,name){const a=document.createElement("a"),u=URL.createObjectURL(blob);a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
$("exportSvg").onclick=()=>{download(new Blob([clean()],{type:"image/svg+xml"}),"icon.svg");toast("SVG exportado")};$("exportPng").onclick=()=>{const im=new Image(),u=URL.createObjectURL(new Blob([clean()],{type:"image/svg+xml"}));im.onload=()=>{const c=document.createElement("canvas");c.width=c.height=docSize;c.getContext("2d").drawImage(im,0,0);c.toBlob(b=>download(b,"icon.png"),"image/png");URL.revokeObjectURL(u);toast("PNG exportado")};im.src=u};
window.onkeydown=e=>{if(["INPUT","SELECT","TEXTAREA"].includes(document.activeElement.tagName))return;const k=e.key.toLowerCase(),mod=e.ctrlKey||e.metaKey;if(mod&&k==="z"){e.preventDefault();restore(historyIndex-(e.shiftKey?-1:1));return}if(mod&&k==="y"){e.preventDefault();restore(historyIndex+1);return}if(mod&&k==="d"){e.preventDefault();dup();return}if(mod&&k==="c"){e.preventDefault();copySelection();return}if(mod&&k==="v"){e.preventDefault();pasteSelection();return}if((e.key==="Delete"||e.key==="Backspace")&&selected){e.preventDefault();del();return}if(["v","r","e","l","t","p","i"].includes(k))setTool({v:"select",r:"rect",e:"ellipse",l:"line",t:"text",p:"freehand",i:"eyedropper"}[k]);if(selected&&["arrowleft","arrowright","arrowup","arrowdown"].includes(k)){e.preventDefault();let d=e.shiftKey?10:1;move(selected,k==="arrowleft"?-d:k==="arrowright"?d:0,k==="arrowup"?-d:k==="arrowdown"?d:0);drawSel();sync();snapshot()}};
loadLocal();syncBackgroundUI();[...objects.children].forEach(ensure);layers();snapshot();setTimeout(()=>$("zoomFit").click(),0);